applications:
  in-app_clamav:
    source:
      root: "/"
    stack:
      - "clamav"
    build:
      flavor: none
    container_profile: BALANCED

    mounts:
      'folder2scan':
        source: storage
        source_path: folder2scan
      'var':
        source: storage
        source_path: var

    hooks:
      build: |
        set -eux
        ./scripts/systemd_install.sh
      deploy: |
        set -eux
        ./scripts/clam_install.sh
        echo "Create fake file for test (can be remove !)"
        ./scripts/clam_populate.sh

    crons:
      update-db:
        spec: '0 0 * * *'
        commands:
          start: ./scripts/clam_update-db.sh
          stop: pkill freshclam

      scan-files:
        spec: 'H * * * *'
        commands:
          start: ./scripts/clam_scan.sh
          stop: pkill clamscan
    
    workers:
      service_clamav:
        commands:
          start: |
            ./scripts/clam_install.sh
            ./scripts/clam_update-db.sh
            ./scripts/systemd_init.sh

    operations:
      trigg_clamav:
        role: viewer
        commands:
          start: |
            ./scripts/clam_scan-clt.sh            

services: null
routes:
  # "https://{default}/":
  #   type: upstream
  #   upstream: "test-clamav:http"
